### ISSUE TITLE
Staging and Deployments

### ISSUE THREAD

**Issue by nick-telsan** [Good-Bids/goodbids#274]
# Context

We now have a staging branch. We need to be able to deploy to it!

# Tasks

- [ ] Add release and pre-release workflows to push to WPVIP
  - Release workflow deploys to production
  - Pre-release workflow deploys to staging
- [ ] Update CircleCI to build staging
- [ ] Add documentation on release workflows
