### ISSUE TITLE
Bidding Block Polling Mode

### ISSUE THREAD

**Issue by nick-telsan** [Good-Bids/goodbids#280]
# Context

If Auctioneer is unavailable for any reason, we should swap to polling mode.

## Tasks
- [ ] On error, swap to polling mode
- [ ] In polling mode, either
  - Render a "Polling" component
  - Adjust the Fetcher Components `useGetAuction` hook to poll
- [ ] Poll every 30 seconds
- [ ] Every minute, try to reconnect to Auctioneer
- [ ] Add a subtle message if we're in polling mode
