### ISSUE TITLE
Use integers for auction start/update/end

### ISSUE THREAD

**Issue by nick-telsan** [Good-Bids/goodbids#308]
# Context

## Related
- https://github.com/Good-Bids/goodbids/issues/305#issuecomment-1917311585
- https://github.com/Good-Bids/goodbids-node/issues/33

The auction block only gets an auction id, not a guid.

So Auctioneer won't ever have the appropriate id. We need to update the start/update/end requests to send an integer id instead of a guid.

## Tasks
- [ ] Update start request to use integer id
- [ ] Update update request to use integer id
- [ ] Update end request to use integer id
