### ISSUE TITLE
Webpack upgrade

### ISSUE THREAD

**Issue by nick-telsan** [Good-Bids/goodbids#399]
# Context

We started using Vite for our JS bundling, but we're using Webpack for React. Let's clean these up so that you only need Webpack.

# Tasks
- [ ] Move all Vite-managed JS to Webpack
- [ ] Adjust bin scripts to build JS assets
- [ ] Adjust bin scripts for local JS dev
- [ ] Remove unused Vite configuration in WP.
