### ISSUE TITLE
Admins can clone auctions

### ISSUE THREAD

**Issue by clatwell** [Good-Bids/goodbids#763]
Anne Marie combed through our V1 Spec doc and found one feature that we missed: giving site Admins the ability to clone / duplicate an auction. My idea, [outlined here](https://goodbids.discourse.group/t/feedback-requested-clone-auctions/548), is to add a "Clone" link to the Auction index table in WordPress which kicks the Admin into the Auction Wizard and pre-fills / copies over Reward Product and Auction data from the original form into the Auction wizard form and allows the Admin to step through the wizard and adjust any of the Reward / Auction data from the copied records before creating / saving a new Auction. 

The big trick here is that we'll need to also copy over any page blocks added to the original Auction post type, ie. if the Admin added a video to Auction A, below the Auction Details blocks, they would expect to see that carry over once they create + save the new Auction. 

I suspect this will need to be a collaborative effort between @nick-telsan + @bd-viget + @nathan-schmidt-viget, but it's the last big thing on our list. 

@nick-telsan, can you take the lead on thinking through what needs to happen to make this work / pick up this ticket first, then we can ping-pong it around as needed? 

Thanks, y'all <3 

# Tasks
- [ ] Check url for mode (see #769)
  - If `mode=edit`, use edit view.
  - If `mode=clone`, use clone view.
  - Otherwise, default to create view
  - Q: How do we handle malformed urls (ie `mode=clone` but reward id isn't provided?)
- [ ] Add clone flow
  - Reuse loading state from edit
  - Reuse rest of the states from create
  - Adjust flow so that it goes something like
    Loading -> Review -> (edit reward or auction) -> Finish
- [ ] Add API integration to fetch "parent" auction
- [ ] Adjust copied content to include the new auction id
- [ ] Save and create like a normal create flow
