### ISSUE TITLE
[Bidding Block] Wire up Share GOODBIDS link in Bidding Block to user's referral URL

### ISSUE THREAD

**Issue by clatwell** [Good-Bids/goodbids#811]
This should be a fun one! 

### Context 

- In the Earn Free Bids Component of the Bidding Block, we show underlined text for "share GOODBIDS with a friend." 
- This is currently just static text, but we'd love to be able to link this up to copy the User's referral URL (if they are logged-in) to their clipboard. 

### Tasks 

- [ ] **Return the User's Referral URL in the Get Auction User Details Endpoint** 

@nick-telsan may be able to take a crack at this, otherwise we can ping @bd-viget for notes on how to do this! 

- [ ] **Wire up the User's Referral URL in the Earn Free Bids Component** 

If the current User is logged-in, we'd like the "share GOODBIDS with a friend" text to be a button that copies the referral URL to the User's clipboard. Otherwise, if the User is not logged-in, this should stay as static text. 

- [ ] **Add "Copied" interaction when User clicks copy to clipboard button** 

We don't have specific UI for this, but it would be nice to show some sort of visual indication / interaction on the component after the User clicks the button to indicate that the URL was copied to their clipboard. 

Nathan spun up a nice little interaction for the "Share for free bids" button that we could mirror, but otherwise defer to y'all! 

![Image](https://github.com/Good-Bids/goodbids/assets/16839493/f3dea35c-ce6a-4808-807d-910f5218d31c)
